version: '3.8'
services:
  directory:
    build: ./directory
    networks:
     - grouper
    ports:
    - 389:389
    - 636:636
    volumes:
    - directory_data:/var/lib/ldap
    - directory_config:/etc/ldap/slapd.d
    - ./directory/certs:/container/service/slapd/assets/certs
    environment:
      LDAP_BASE_DN: "dc=test,dc=local"
      LDAP_DOMAIN: "test.local"
#      HOSTNAME: "directory"
      LDAP_TLS_VERIFY_CLIENT: "try"
  database:
    image: postgres:12.3
    command: postgres -N 500
    networks:
      - grouper
    ports:
    - "5432:5432"
    volumes:
    - ./database/initdb.d/:/docker-entrypoint-initdb.d/
    - ./database/data/:/tmp/pdata/
    - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecret
  grouper-ui:
    build: ./grouper
    command: ui
    depends_on:
      - database
      - directory
    networks:
      - grouper
    ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
    - "8443:8443"
    volumes:
      - ./grouper/src/main/docker/slashRoot/opt/grouper/grouperWebapp/WEB-INF/classes/log4j.properties.sample:/opt/grouper/grouperWebapp/WEB-INF/classes/log4j.properties
      - ./grouper/src/main/docker/slashRoot/opt/grouper/grouperWebapp/WEB-INF/classes/grouper.hibernate.properties.sample:/opt/grouper/grouperWebapp/WEB-INF/classes/grouper.hibernate.properties
    environment:
      GROUPER_DATABASE_URL: "jdbc:postgresql://database/grouper"
      GROUPER_DATABASE_USERNAME: "grouper"
      GROUPER_DATABASE_PASSWORD: "grouper"
      GROUPER_MORPHSTRING_ENCRYPT_KEY: "THISISSUPERSECRET!"
      GROUPER_AUTO_DDL_UPTOVERSION: "v5.*.*"
      GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: "true"
      GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES: "0.0.0.0/0"
      GROUPER_UI_GROUPER_AUTH: "true"
      GROUPERSYSTEM_QUICKSTART_PASS: "password"
      RUN_SHIB_SP: "false"
#   grouper-ws:
#     build: ./grouper
#     command: ws
#     depends_on:
#       - database
#       - directory
#     networks:
#       - grouper
#     environment:
#       GROUPER_DATABASE_URL: "jdbc:postgresql://database/grouper"
#       GROUPER_DATABASE_USERNAME: "grouper"
#       GROUPER_DATABASE_PASSWORD: "grouper"
#       GROUPER_MORPHSTRING_ENCRYPT_KEY: "THISISSUPERSECRET!"
#       GROUPER_AUTO_DDL_UPTOVERSION: "v2.5.*"
#       GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: "true"
#       RUN_SHIB_SP: "false"
#       GROUPER_WS_GROUPER_AUTH: "true"
  grouper-daemon:
    build: ./grouper
    command: daemon
    depends_on:
      - database
      - directory
    networks:
      - grouper
    environment:
      GROUPER_DATABASE_URL: "jdbc:postgresql://database/grouper"
      GROUPER_DATABASE_USERNAME: "grouper"
      GROUPER_DATABASE_PASSWORD: "grouper"
      GROUPER_MORPHSTRING_ENCRYPT_KEY: "THISISSUPERSECRET!"
      GROUPER_AUTO_DDL_UPTOVERSION: "v5.*.*"
  ad:
    build:
      context: ./ad/
    cap_add:
      - CAP_SYS_ADMIN
    healthcheck:
      test: netstat -an | grep :3268 | grep LISTEN
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
     - DOMAIN=ad.test.local
     - DOMAINPASS=password
    hostname: dc1
    networks:
      grouper:
        aliases:
          - dc1.ad.test.local
    volumes:
     - ad_samba_data:/var/lib/samba
     - ad_samba_cfg:/etc/samba/external
    expose:
      - 445
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137-138:137-138/udp
      - 139:139
      - 389:389
      - 1389:389/udp
      - 464:464
      - 464:464/udp
      - 1636:636
      - 3268-3269:3268-3269

networks:
  grouper:
volumes:
  database_data:
    driver: local
  directory_data:
    driver: local
  directory_config:
    driver: local
  ad_samba_data:
    driver: local
  ad_samba_cfg:
    driver: local
#secrets:

